version: '3'
services:
  web:
    image: nginx:1.20.1
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./src:/var/www/html/src:delegated
  app:
    build: ./docker/php
    working_dir: /var/www/html/src
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html:delegated
  mysql:
    image: mysql:8.0.26
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lotbot
      MYSQL_USER: lotbot
      MYSQL_PASSWORD: lotbot
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:delegated
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d:delegated
  node:
    image: node:14.17.6
    command: npm run watch
    tty: true
    volumes:
      - ./src:/var/www/html/src:delegated
    working_dir: /var/www/html/src
volumes:
  mysql-data: